### ISSUE TITLE
Some UI improvements

### ISSUE THREAD

**Issue by sallymoc** [qubic/quottery-frontend#11]
![image](https://github.com/qubic/quottery-frontend/assets/231888/81910604-cbbe-4b9a-83e7-f8037c5449c2)
![image](https://github.com/qubic/quottery-frontend/assets/231888/9dc707d3-8a69-4bd9-b3de-ebb10c62501b)
![image](https://github.com/qubic/quottery-frontend/assets/231888/f736e7ab-c6d9-46a2-b9da-8705fb106d17)
![image](https://github.com/qubic/quottery-frontend/assets/231888/58d96770-177b-41f0-9b17-f99416042e9d)
![image](https://github.com/qubic/quottery-frontend/assets/231888/cf895676-b11f-4028-924a-c9a8193fedbe)

**Comment by ddresch** [comment]
List of Todos:

- [ ] add label to unlock icon 
- [ ] center text of pot size info
- [ ] add common icon for filter bets dropdown
- [ ] center value of "slots taken" info
- [ ] show disabled BET! button if <0
- [ ] remove "unneeded empty space"
- [ ] remove NaN in option buttons
- [ ] adjust font style for Cancel or use X icon in action button
