### ISSUE TITLE
Test assignment for ideal candidate

### ISSUE THREAD

**Issue by konan-5** [qubic/quottery-frontend#3]
# Overview
Quottery is a betting project and you can find detailed information about that from following docs https://docs.google.com/document/d/1kUUvgXAnA94BSEzvuR8evWG9zzCQ_19edPSQt8oYiMU/edit

# Task 1
Create quottery project and add the first page using mock data
https://www.figma.com/design/uTkCAs5q8c1UiV9PPPRGcS/Qubic-Apps?node-id=0-6
![image](https://github.com/qubic/quottery-frontend/assets/148735980/31dbab5b-aa07-4b38-9d22-bb009aac894b)

# Task 2
Create the first draft of qubic react component library as much as possible by taking the css, components and so on from explorer project
https://github.com/qubic/explorer-frontend
https://github.com/qubic/ts-react-library
both should be achieve in 1~2 business day even without any knowledge yet.

**Comment by AndyQus** [comment]
everything is implemented differently
