### ISSUE TITLE
Integrate footer from Explorer to display versioning and terms and conditions

### ISSUE THREAD

**Issue by AndyQus** [qubic/quottery-frontend#7]
![image](https://github.com/qubic/quottery-frontend/assets/157237454/aa542d0a-5834-44b1-98e1-d339dd9ddbb9)

**Comment by AndyQus** [comment]
https://github.com/qubic/explorer-frontend/blob/main/src/app/main/apps/network/overview/Overview.js

**Comment by couch42** [comment]
See 2841a8c3beeb9e50702338cffee663556c4ecfa0 is done.
